# mongodb://davidmine:password@localhost:27017/admin

version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=davidmine
      - MONGO_INITDB_ROOT_PASSWORD=password
